export declare const CEMIConstants: {
    PL_MEDIUM_INFO: number;
    RF_MEDIUM_INFO: number;
    BUSMONITOR_STATUS_INFO: number;
    TIMESTAMP_RELATIVE: number;
    TIME_DELAY_TILL_SENDING: number;
    EXTENDED_RELATIVE_TIMESTAMP: number;
    BIBAT_INFO: number;
    RF_MULTI_INFO: number;
    PREAMBLE: number;
    POSTAMBLE: number;
    RF_FASK_ACK_INFO: number;
    MANUFACTURER_SPECIFIC_INFO: number;
    L_DATA_REQ: number;
    L_DATA_CON: number;
    L_DATA_IND: number;
    GROUP_READ: number;
    GROUP_RESPONSE: number;
    GROUP_WRITE: number;
    INDIVIDUAL_WRITE: number;
    INDIVIDUAL_READ: number;
    INDIVIDUAL_RESPONSE: number;
    TPCI_UNUMBERED_PACKET: number;
};
